os: linux
language: ruby
rvm:
  - 2.6.3

before_install:
  - gem install bundler

install:
  - bundle install

before_script:
  - chmod +x ./scripts/build

script: ./scripts/build

branches:
  only:
    - release

cache: bundler

deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: _site/
  target_branch: master
  token: $GITHUB_API_KEY
  on:
    branch: release

notifications:
  email:
    on_success: never
    on_failure: always
