### Site Settings ###
title: Alessio Falai
description: >-
  "I love keyboards :keyboard:, 
  open-source software :penguin: and 
  learning something new everyday :open_book:."
url: "alessiofalai.it"
baseurl: ""
repository: Wadaboa/wadaboa.github.io
remote_theme: YoussefRaafatNasry/portfolYOU

### Build Settings ###
plugins:
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-paginate
  - jemoji
  - jekyll-remote-theme
  - jekyll-admin
  - jekyll-sitemap

### Navbar Settings ###
nav_exclude:
  - 404.html
  - index.html
  - blog/tags.html
  - blog/page-:num/index.html

### Author Info ###
author:
  name: Alessio Falai
  image: https://avatars3.githubusercontent.com/u/1256055?s=460&v=4
  email: falai.alessio@gmail.com
  facebook: wadaboa
  github: Wadaboa
  instagram: Wadaboa
  linkedin: alessio-falai
  # medium: your_username
  # soundcloud: your_username
  # spotify: your_username
  # stackoverflow: your_user_id
  # tumblr: your_username.tumblr.com
  # twitch: your_username
  # twitter: your_username
  # vimeo: your_username
  # youtube: your_channel_name

### Pagination ###
paginate: 6
paginate_path: "/blog/page-:num/"

### Posts Permalink ###
permalink: blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - portfolyou-jekyll-theme.gemspec
  - Gemfile.lock
  - vendor
